server:
  port: 8769

spring:
  application:
    name: euraka-peer2-server

eureka:
  instance:
    hostname: peer2
  client:
    fetch-registry: false
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/