server:
  port: 8087

#服务与服务之间相互调用一般都是根据这个name
spring:
  application:
    name: eurekafirst

eureka:
  client:
    service-url:
      defaultZone: http://localhost:11111/eureka/
#       defaultZone: http://peer2:11113/eureka/